### ISSUE TITLE
[ui] scale/zoom in or out for each graph?

### ISSUE THREAD

**Issue by yswalker** [arl/statsviz#48]
I want to zoom out and explore more metrics in the past. Can you please provide such feature?

**Comment by arl** [comment]
Hey @yswalker . 
Thanks for your interest in statsviz and for the request
Yeah such improvements are in the roadmap, I'd like users to be able to increase data retention and improve the UI in order to browse metrics over a longer time scale than what we can currently do.
I don't have an ETA though

**Comment by arl** [comment]
@yswalker  FYI the new version has a time range selector so that you can choose from:
 - last minute
 - last 5 minutes
 - last 10 minutes

At the moment, you can only see the full time range and now, for example, zoom on a specific 2 minutes. That's something that is planned.
Anyway, I think that new feature released is already a big move forward what you were asking.
I'm gonna close this issue, feel free to open a new one, or reopen, in case.
Thank you
